spring:
  data:
    rest:
      base-path: /api
    mongodb:
      uri: "mongodb+srv://meraklis:MVNK5EWBTdsPA0Ac@cluster0.9fdjv.mongodb.net"
      database: "icare"
  autoconfigure:
    exclude[0]: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
    exclude[1]: org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
#  security:
#    user:
#      name: justin
#      password: something
#      roles: manager
