spring:
  data:
    rest:
      base-path: /api
    mongodb:
      uri: ${MONGODB_URI}
      database: "icare"
okta:
  oauth2:
    issuer: ${AUTH0_ISSUER}
    client-id: ${AUTH0_CLIENT_ID}
    client-secret: ${AUTH0_CLIENT_SECRET}
